// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHI5NI8utzciX9vSHs9VzC6Rlw2hOkjeM',
    appId: '1:58962312509:web:2fc3b4f95408e0cbce5954',
    messagingSenderId: '58962312509',
    projectId: 'myapp-f1de6',
    authDomain: 'myapp-f1de6.firebaseapp.com',
    databaseURL: 'https://myapp-f1de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-f1de6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vWRAEtQvafxUFa2UdMdHoMQoqKzw6Qo',
    appId: '1:58962312509:android:31f37bd95063f7dbce5954',
    messagingSenderId: '58962312509',
    projectId: 'myapp-f1de6',
    databaseURL: 'https://myapp-f1de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-f1de6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmu0D8rFH9DVtia0WlbV4xv-3G6Y7HFcY',
    appId: '1:58962312509:ios:0e718a84313b5fa0ce5954',
    messagingSenderId: '58962312509',
    projectId: 'myapp-f1de6',
    databaseURL: 'https://myapp-f1de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-f1de6.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmu0D8rFH9DVtia0WlbV4xv-3G6Y7HFcY',
    appId: '1:58962312509:ios:0e718a84313b5fa0ce5954',
    messagingSenderId: '58962312509',
    projectId: 'myapp-f1de6',
    databaseURL: 'https://myapp-f1de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-f1de6.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHI5NI8utzciX9vSHs9VzC6Rlw2hOkjeM',
    appId: '1:58962312509:web:f15bed90945e32b4ce5954',
    messagingSenderId: '58962312509',
    projectId: 'myapp-f1de6',
    authDomain: 'myapp-f1de6.firebaseapp.com',
    databaseURL: 'https://myapp-f1de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-f1de6.appspot.com',
  );

}